name: dc-apply

on:
  push:
    branches:
      - "**"
    paths:
      - "terraform/**"
      - "ansible/**"
      - ".gitea/workflows/**"
  workflow_dispatch: {}

jobs:
  plan:
    # Run on pushes to non-main branches: validate/plan only (no apply)
    if: ${{ gitea.event_name == 'push' && gitea.ref != 'refs/heads/main' }}
    runs-on: linux
    defaults:
      run:
        shell: bash
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_proxmox_endpoint: ${{ vars.TF_VAR_proxmox_endpoint }}
      TF_VAR_proxmox_api_token: ${{ secrets.TF_VAR_proxmox_api_token }}
      TF_VAR_proxmox_tls_insecure: ${{ vars.TF_VAR_proxmox_tls_insecure }}
      TF_VAR_ssh_public_key: ${{ vars.TF_VAR_ssh_public_key }}

      # MinIO creds for Terraform S3 backend
      AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      AWS_EC2_METADATA_DISABLED: "true"

      ANSIBLE_CONFIG: ansible.cfg
      ANSIBLE_HOST_KEY_CHECKING: ${{ vars.ANSIBLE_HOST_KEY_CHECKING }}

    steps:
      - name: Checkout repository
        run: |
          set -euo pipefail
          rm -rf ./* ./.git || true

          git clone "http://gitgard.home.arpa:3000/smittyman/stack-samba4-dc.git" .
          git fetch --all --tags --prune

          # Checkout the triggering SHA when available (push event)
          SHA="${GITHUB_SHA:-${GITEA_SHA:-}}"
          if [ -n "${SHA}" ]; then
            echo "Checking out SHA: ${SHA}"
            git checkout -f "${SHA}"
          fi

          git rev-parse --short HEAD
          git log -1 --oneline

      - name: Fetch infra-platform base role
        run: |
          set -euo pipefail
          rm -rf /tmp/infra-platform
          git clone --depth 1 --branch v0.1.3 "http://gitgard.home.arpa:3000/smittyman/infra-platform.git" /tmp/infra-platform
          rm -rf ansible/roles/base
          mkdir -p ansible/roles
          cp -a /tmp/infra-platform/ansible/roles/base ansible/roles/

      - name: Verify tools
        run: |
          terraform -version
          ansible --version
          python3 --version

      - name: Terraform init
        working-directory: terraform/envs/home
        run: terraform init

      - name: Terraform validate
        working-directory: terraform/envs/home
        run: terraform validate

      - name: Terraform plan (no apply)
        working-directory: terraform/envs/home
        run: terraform plan -no-color

      # Syntax-check playbooks (does not require vault secrets)
      - name: Ansible syntax check (base)
        working-directory: ansible
        run: ansible-playbook -i inventories/home/inventory.ini playbooks/base.yml --syntax-check

      - name: Ansible syntax check (samba DC)
        working-directory: ansible
        run: ansible-playbook -i inventories/home/inventory.ini playbooks/samba_dc.yml --syntax-check

  apply:
    # Run on push to main OR manual run
    if: ${{ (gitea.event_name == 'push' && gitea.ref == 'refs/heads/main') || gitea.event_name == 'workflow_dispatch' }}
    runs-on: linux
    defaults:
      run:
        shell: bash
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_proxmox_endpoint: ${{ vars.TF_VAR_proxmox_endpoint }}
      TF_VAR_proxmox_api_token: ${{ secrets.TF_VAR_proxmox_api_token }}
      TF_VAR_proxmox_tls_insecure: ${{ vars.TF_VAR_proxmox_tls_insecure }}
      TF_VAR_ssh_public_key: ${{ vars.TF_VAR_ssh_public_key }}

      # MinIO creds for Terraform S3 backend
      AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      AWS_EC2_METADATA_DISABLED: "true"

      ANSIBLE_CONFIG: ansible.cfg
      ANSIBLE_HOST_KEY_CHECKING: ${{ vars.ANSIBLE_HOST_KEY_CHECKING }}
      ANSIBLE_PRIVATE_KEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

    steps:
      - name: Checkout repository
        run: |
          set -euo pipefail
          rm -rf ./* ./.git || true

          git clone "http://gitgard.home.arpa:3000/smittyman/stack-samba4-dc.git" .
          git fetch --all --tags --prune

          # Checkout the triggering SHA when available
          SHA="${GITHUB_SHA:-${GITEA_SHA:-}}"
          if [ -n "${SHA}" ]; then
            echo "Checking out SHA: ${SHA}"
            git checkout -f "${SHA}"
          fi

          git rev-parse --short HEAD
          git log -1 --oneline

      - name: Fetch infra-platform base role
        run: |
          set -euo pipefail
          rm -rf /tmp/infra-platform
          git clone --depth 1 --branch v0.1.3 "http://gitgard.home.arpa:3000/smittyman/infra-platform.git" /tmp/infra-platform
          rm -rf ansible/roles/base
          mkdir -p ansible/roles
          cp -a /tmp/infra-platform/ansible/roles/base ansible/roles/

      - name: Verify tools
        run: |
          terraform -version
          ansible --version
          python3 --version

      - name: Terraform init
        working-directory: terraform/envs/home
        run: terraform init

      - name: Terraform apply
        working-directory: terraform/envs/home
        run: terraform apply -auto-approve

      - name: Generate Ansible inventory from Terraform output
        run: |
          set -euo pipefail

          terraform -chdir=terraform/envs/home output -json hosts > /tmp/hosts.json

          python3 terraform/scripts/tfhosts_to_inventory.py \
            --tf-dir terraform/envs/home \
            --out ansible/inventories/home/inventory.ini \
            --init

      - name: Write SSH key and vault password
        run: |
          install -m 700 -d ~/.ssh
          printf "%s\n" "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printf "%s\n" "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /tmp/.vault_pass
          chmod 600 /tmp/.vault_pass

          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Write all.vault.yml from secret
        working-directory: ansible
        run: |
          set -euo pipefail
          install -d -m 755 inventories/home/group_vars
          printf "%s\n" "${{ secrets.ANSIBLE_ALL_VAULT_YML }}" > inventories/home/group_vars/all.vault.yml
          chmod 600 inventories/home/group_vars/all.vault.yml
          ls -la inventories/home/group_vars

      - name: Write samba_dc.vault.yml from secret
        working-directory: ansible
        run: |
          set -euo pipefail
          install -d -m 755 inventories/home/group_vars
          printf "%s\n" "${{ secrets.ANSIBLE_SAMBA_DC_VAULT_YML }}" > inventories/home/group_vars/samba_dc.vault.yml
          chmod 600 inventories/home/group_vars/samba_dc.vault.yml
          ls -la inventories/home/group_vars

      - name: Run Ansible (base VM setup)
        working-directory: ansible
        run: |
          ansible-playbook -i inventories/home/inventory.ini playbooks/base.yml \
            --vault-password-file /tmp/.vault_pass

      - name: Run Ansible (samba DC config)
        working-directory: ansible
        run: |
          ansible-playbook -i inventories/home/inventory.ini playbooks/samba_dc.yml \
            --vault-password-file /tmp/.vault_pass
